ALTER AUTHORIZATION ON SCHEMA::dcagapsuser TO dbo;
ALTER AUTHORIZATION ON SCHEMA::dcagaps_rep_user TO dbo;
GO

DROP USER IF EXISTS [OPSCS\gaps2rpa];
DROP USER IF EXISTS dcagapsuser;
DROP USER IF EXISTS dcagaps_rep_user;
DROP USER IF EXISTS micarder;
DROP USER IF EXISTS dcagapsrpts;
DROP USER IF EXISTS OPT_Extract;
DROP USER IF EXISTS SDP_Extract;

DROP VIEW IF EXISTS dbo.VW_ACTIVE_USER_SESSION_STATE;
DROP VIEW IF EXISTS dbo.VW_ACTIVE_USER;
DROP VIEW IF EXISTS dbo.VW_RPT_UNAVAILBILTY;

DROP PROCEDURE IF EXISTS dbo.sp_sysindexes_info;
DROP PROCEDURE IF EXISTS dbo.xan_TestDataMV;
DROP PROCEDURE IF EXISTS dbo.xan_List_FailedJobs;
DROP PROCEDURE IF EXISTS dbo.xan_List_SuccessfulJobs;
GO
